#!/bin/bash
##Move to /home directory
echo "Changing Directory..."
cd
#

##Ruby and git
echo "Installing dependencies"
sudo apt-get install git ruby nmap curl -y > /dev/null
#

##Fix possible previous attempts to install metasploit/armitage
echo "Fixing possible previous mistakes... (no offense)"
echo "File does not exist errors are common here, this just means you haven't installed Metasploit previously."
echo "Those errors will not impact the install."
sudo apt-get remove metasploit-framework postgresql --purge -y > /dev/null
sudo rm -r /opt/metasploit-framework > /dev/null
sudo rm -r /opt/armitage > /dev/null
sudo rm -r /usr/local/bin/armitage > /dev/null
sudo rm -r /usr/local/bin/teamserver > /dev/null



##Install metasploit
echo "Installing Metasploit-Framework... (This may take some time)"
echo "Doing other Metasploit installation requirement things... (This WILL take some time)"
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
chmod 755 msfinstall && \
./msfinstall
#

##Man install armitage
echo "Installing Armitage..."
curl -# -o /tmp/armitage.tgz http://www.fastandeasyhacking.com/download/armitage150813.tgz > /dev/null
sudo tar -xvzf /tmp/armitage.tgz -C /opt > /dev/null
sudo ln -s /opt/armitage/armitage /usr/local/bin/armitage > /dev/null
sudo ln -s /opt/armitage/teamserver /usr/local/bin/teamserver > /dev/null
sudo sh -c "echo java -jar /opt/armitage/armitage.jar \$\* > /opt/armitage/armitage" > /dev/null
sudo perl -pi -e 's/armitage.jar/\/opt\/armitage\/armitage.jar/g' /opt/armitage/teamserver > /dev/null
#

##Create database.yml file
sudo sh -c "echo export MSF_DATABASE_CONFIG=~/.msf4/database.yml >> /etc/profile"
source /etc/profile > /dev/null
sudo chown -R `whoami` ~/.msf4
#

##Thank the user
echo "So... That should be it, run 'sudo -E armitage' to start armitage and 'sudo msfconsole' to start metasploit"
echo "Thanks for using my program!"
echo "Written by https://github.com/matt-london"
#
